"""Some changes

Revision ID: edf3533313f2
Revises: 064d13c85cd9
Create Date: 2026-05-26 23:12:49.130664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf3533313f2'
down_revision: Union[str, Sequence[str], None] = '064d13c85cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_devices', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_devices', sa.Column('total_logins', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('uuid', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_column('users', 'uuid')
    op.drop_column('user_devices', 'total_logins')
    op.drop_column('user_devices', 'last_seen_at')
    # ### end Alembic commands ###
